call plug#begin('~/.local/share/nvim/site/plugged')


Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-jedi'
Plug 'carlitux/deoplete-ternjs'
Plug 'shougo/echodoc'

Plug 'tpope/vim-sleuth'
Plug 'nathanaelkane/vim-indent-guides'

Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'itchyny/lightline.vim'


Plug 'neomake/neomake'
Plug 'mileszs/ack.vim'
Plug 'amix/open_file_under_cursor.vim'

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'vim-scripts/nginx.vim'


call plug#end()

let g:deoplete#enable_at_startup = 1
let g:echodoc_type = 'signature'
let g:python3_host_prog = system('echo -n $(which python3)') " expand('/usr/bin/python3')


" NERDTree mappings {{{
map <C-n> :NERDTreeToggle<CR>
" }}}

" NERDTree {{{
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '__pycache__']
" }}}

set cmdheight=2
set background=dark
set number
set cursorline
set wildmenu
set noswapfile
set ignorecase


colorscheme peaksea
