" pip install neovim
" pip install 'python-language-server[all]'
" rustup component add rls-preview rust-analysis rust-src

call plug#begin('~/.local/share/nvim/site/plugged')

Plug 'autozimu/LanguageClient-neuovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }


Plug 'Shougo/deoplete.nvim', {'do':':UpdateRemotePlugins'}
Plug 'shougo/echodoc'
Plug 'ervandew/supertab'

Plug 'tpope/vim-sleuth'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'

Plug 'neomake/neomake'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'vim-scripts/nginx.vim'

Plug 'sheerun/vim-polyglot'
Plug 'joshdick/onedark.vim'

call plug#end()


let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('_', 'disabled_syntaxes', ['Comment', 'String'])
let g:deoplete#sources = {}
let g:deoplete#sources.rust = ['LanguageClient']

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'python': ['pyls'],
    \ }
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

call neomake#configure#automake('w')
let g:neomake_open_list = 2

let g:echodoc_type = 'signature'
let g:echodoc#enable_at_startup = 1
set completeopt-=preview
let g:python3_host_prog = system('echo -n $(which python3)') " expand('/usr/bin/python3')



map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '__pycache__']

set hidden
set laststatus=2 " for lightline.vim
set cmdheight=2
set background=dark
set number
set cursorline
set wildmenu
set noswapfile
set ignorecase

let $NVIM_TUI_ENABLE_TRUE_COLOR=1
set termguicolors
syntax on
colorscheme onedark
